# Generated by Django 5.0.6 on 2024-06-22 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='developer',
            table='developer',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
